language: python

python:
  - "2.7"

virtualenv:
    system_site_packages: true

install:
    #- sudo mkdir /sw
    #- sudo mkdir /sw/include
    #- sudo mkdir /sw/
    #- sudo chmod -vR 775 /sw
    - wget ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/cfitsio3370.tar.gz
    - tar -zxvf cfitsio3370.tar.gz
    - cd cfitsio
    - ./configure -prefix=/sw
    - make
    - sudo make install
    - cd ..
    - C_INCLUDE_PATH=/sw/include
    - LIBRARY_PATH=/sw/lib
    - export C_INCLUDE_PATH
    - export LIBRARY_PATH
    - echo $C_INCLUDE_PATH
    - echo $LIBRARY_PATH
    - ls /
    - ls /sw/
    - ls /sw/inlcude
    - ls /sw/lib
    - pip install stwcs
    - python setup.py install

script:
    - nosetests tests/unit_tests

