## This is a template settings.yaml file. 
## Uncomment anything with a single # and modify the values for you setup.

# Database Settings
db_connection: mysql+pymysql://root:user@localhost/mtpipeline
db_echo: False

# Email Settings
email_switch: True
contact_email: user@institute.edu

# File System Settings
acs_input_path: /absolute/path/to/files
acs_output_path: /absolute/path/to/files
wfc3_input_path: /absolute/path/to/files
wfc3_output_path: /absolute/path/to/files
wfpc2_input_path: /absolute/path/to/files
wfpc2_output_path: /absolute/path/to/files
logging_path: /absolute/path/to/files

# Number of Cores
num_cores: number_of_cores
